### PR TITLE
make android modifications automatically

### PR DESCRIPTION
**Pull request by miqmago**
Now it makes the changes automatically.

### CODE REVIEW

**Comment by bjesuiter** [comment]
Thanks for your contribution! I'll take a look at it.

**Comment by bjesuiter** [comment]
@miqmago This looks fine for me on first sight. 

Have you tested this on a project of yours and if yes, can you show that it works as intended? 
Since I don't do Ionic / capacitor development currently, I've no test project laying around.

**Comment by miqmago** [comment]
I've added a test case too :)

**Comment by bjesuiter** [comment]
Thank you very much! will merge it and deploy it right away!

**Pull request merged**
